import {
  getUsers,
  login,
  refreshToken,
  signup,
  activation,
  logout,
  forgotPassword,
  resetPassword,
  changePassword,
  changeUserDetails,
  changeEmail,
  verifyEmail,
  deleteUser,
  getUserDetails,
} from "./user";

import {
  makeProfile,
  uploadAvatar,
  uploadDocument,
  getFreelancers,
  searchFreelancer,
  getFreelancerDetails,
  me,
  changeFreelancerDetails,
  addEmployment,
  updateEmployment,
  verifyPhoneNumber,
  confirmPhoneNumber,
} from "./freelancer";

export const UserController = {
  getUsers,
  login,
  refreshToken,
  signup,
  activation,
  logout,
  forgotPassword,
  resetPassword,
  changePassword,
  changeUserDetails,
  changeEmail,
  verifyEmail,
  deleteUser,
  getUserDetails,
};

export const FreelancerController = {
  makeProfile,
  uploadAvatar,
  uploadDocument,
  getFreelancers,
  searchFreelancer,
  getFreelancerDetails,
  me,
  changeFreelancerDetails,
  addEmployment,
  updateEmployment,
  verifyPhoneNumber,
  confirmPhoneNumber,
};
