export const SIGNUP_USER_TYPE = "SIGNUP_USER_TYPE";
export const SIGNUP_USER_CREDENTIALS = "SIGNUP_USER_CREDENTIALS";
export const SIGNUP_STATUS = "SIGNUP_STATUS";
export const SIGNING_UP = "SIGNING_UP";
export const SIGNUP_RESULT = "SIGNUP_RESULT";

export const SIGNIN = "SIGNIN";
export const SIGNIN_STATUS = "SIGNIN_STATUS";
export const SIGNING_IN = "SIGNING_IN";
export const SIGNIN_CLOSE_MODAL = "SIGNIN_CLOSE_MODAL";
export const SIGNIN_REDIRECT = "SIGNIN_REDIRECT";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const CHECK_PROFILE = "CHECK_PROFILE";
export const CHECK_PROFILE_STATUS = "CHECK_PROFILE_STATUS";
export const CHECKING_PROFILE = "CHECKING_PROFILE";
export const CHECK_PROFILE_REDIRECT = "CHECK_PROFILE_REDIRECT";
export const CHECK_PROFILE_ERROR = "CHECK_PROFILE_ERROR";
